'use strict';

// Byte-exact MAVLink frames from an INDEPENDENT reference implementation.
//
// Why this file exists. test/telemetry.test.js builds its test frames by calling
// picar's own CRC functions — the same ones the parser uses to validate. So it
// generates frames with whatever algorithm picar has and then checks them against
// that algorithm. A Codex review demonstrated the consequence: changing the
// production CRC seed from 0xFFFF to 0x0000 left the whole suite green, because
// both sides of the comparison changed together. A test that cannot distinguish a
// correct CRC from a broken one is not testing the CRC.
//
// The fixtures below were generated on rover3 with **pymavlink 2.4.49** — the same
// library MAVProxy itself uses — via
// pymavlink.dialects.v20.ardupilotmega / v10.ardupilotmega, then pasted here as
// hex. Nothing in picar produced them. If picar's CRC seed, CRC_EXTRA table, field
// offsets, header layout or zero-extension are wrong, these frames fail to decode.
//
// Note the v2 payload lengths: sys_status is 0x11 (17 bytes, zero-trimmed from its
// declared 31) and power_status is 0x05 (trimmed from 6). That is exactly the
// truncation observed on the live wire, so these fixtures exercise zeroExtend()
// against real reference output rather than a hand-built approximation.

const test   = require('node:test');
const assert = require('node:assert/strict');

const PWMMavproxy = require('../pwm_mavproxy_servo.js');

// Generated by pymavlink 2.4.49 on rover3, 2026-08-03. Do NOT regenerate these
// with picar's own builders — that would defeat the entire point of the file.
const VECTORS = {
  v1: {
    heartbeat:    'fe0900010100000000000b038104037600',
    sys_status:   'fe1f00010101000000000000000000000000fa00121f2e0000000000000000000000000000bca1',
    power_status: 'fe060001017d2b147e1725001d2e',
    radio_status: 'fe090001016d02000100b4aa5f282377ec',
  },
  v2: {
    heartbeat:    'fd090000000101000000000000000b03810403ecc3',
    sys_status:   'fd110000000101010000000000000000000000000000fa00121f2e9b5f',
    power_status: 'fd0500000001017d00002b147e17259dd0',
    radio_status: 'fd0900000001016d000002000100b4aa5f28238c5f',
  },
};

// The values pymavlink was asked to encode. Decoding must recover exactly these.
const ENCODED = {
  heartbeat:    { type: 11, autopilot: 3, base_mode: 129 },
  sys_status:   { voltage_mV: 7954, current_cA: 46, remaining: 0 },
  power_status: { Vcc_mV: 5163, Vservo_mV: 6014, flags: 37 },
  radio_status: { rssi: 180, remrssi: 170, txbuf: 95, noise: 40, remnoise: 35, rxerrors: 2, fixed: 1 },
};

function driver(extra = {}) {
  return new PWMMavproxy({ mavproxy_autostart: false, ...extra });
}
function feed(d, hex) {
  d.parseIncoming(Buffer.from(hex, 'hex'));
}

// Recompute a frame's checksum after tampering with its header.
//
// This matters more than it looks. A first draft of the header tests below simply
// flipped a byte and asserted the frame was rejected — and they passed whether or
// not the check under test existed, because flipping the byte ALSO invalidated the
// checksum, so the CRC rejected the frame first. Three tests that proved nothing.
// (Mutation testing caught it: deleting the incompat-flag and sysId checks left
// them green.)
//
// So an isolating test has to re-seal the frame. Using picar's own CRC here is
// legitimate precisely because the CRC is pinned INDEPENDENTLY by the pymavlink
// reference vectors above — if the CRC implementation were wrong those would fail,
// so this helper cannot hide a broken checksum.
const CRC_EXTRA = { 0: 50, 1: 124, 22: 220, 109: 185, 125: 203 };

function reseal(buf) {
  const out       = Buffer.from(buf);
  const isV2      = out[0] === 0xFD;
  const headerLen = isV2 ? 10 : 6;
  const payloadLen = out[1];
  const msgId = isV2 ? (out[7] | (out[8] << 8) | (out[9] << 16)) : out[5];
  let crc = PWMMavproxy.crc16(
    out.subarray(1, headerLen + payloadLen), headerLen - 1 + payloadLen);
  crc = PWMMavproxy.crcAccumulate(CRC_EXTRA[msgId], crc);
  out.writeUInt16LE(crc, headerLen + payloadLen);
  return out;
}

// Sanity-check the helper itself: re-sealing an untouched reference frame must
// reproduce the checksum pymavlink already put there. If this fails, every test
// built on reseal() is meaningless.
test('reseal() reproduces pymavlink\'s own checksum on an untouched frame', () => {
  for (const version of ['v1', 'v2']) {
    for (const [name, hex] of Object.entries(VECTORS[version])) {
      const raw = Buffer.from(hex, 'hex');
      assert.deepEqual(reseal(raw), raw,
        `${version} ${name}: reseal must be a no-op on a valid reference frame`);
    }
  }
});

for (const version of ['v1', 'v2']) {
  test(`${version}: a reference HEARTBEAT is accepted and decoded`, () => {
    const d = driver();
    feed(d, VECTORS[version].heartbeat);
    assert.notEqual(d.telemetry.heartbeat, null,
      'a valid reference heartbeat must be accepted — if this fails the CRC or header layout is wrong');
    assert.equal(d.telemetry.heartbeat.armed, (ENCODED.heartbeat.base_mode & 0x80) !== 0);
    assert.equal(d.pixhawkHeartbeatSeen, true);
  });

  test(`${version}: a reference SYS_STATUS decodes to the encoded battery values`, () => {
    const d = driver();
    feed(d, VECTORS[version].sys_status);
    assert.notEqual(d.telemetry.battery, null, 'reference SYS_STATUS must be accepted');
    assert.equal(d.telemetry.battery.voltageV, ENCODED.sys_status.voltage_mV / 1000);
    assert.equal(d.telemetry.battery.currentA, ENCODED.sys_status.current_cA / 100);
  });

  test(`${version}: a reference POWER_STATUS decodes to the encoded rail voltages`, () => {
    const d = driver();
    feed(d, VECTORS[version].power_status);
    assert.notEqual(d.telemetry.power, null, 'reference POWER_STATUS must be accepted');
    assert.equal(d.telemetry.power.boardV, ENCODED.power_status.Vcc_mV / 1000);
    assert.equal(d.telemetry.power.servoV, ENCODED.power_status.Vservo_mV / 1000);
    // flags is the LAST field, so it is the one a zero-trimmed v2 payload loses
    // first. A naive fixed-offset read produced 36901 here instead of 37.
    assert.equal(d.telemetry.power.flags, ENCODED.power_status.flags);
  });

  test(`${version}: a reference RADIO_STATUS decodes to the encoded link values`, () => {
    const d = driver();
    feed(d, VECTORS[version].radio_status);
    assert.notEqual(d.telemetry.radio, null, 'reference RADIO_STATUS must be accepted');
    const r = d.telemetry.radio;
    assert.equal(r.rssi,     ENCODED.radio_status.rssi);
    assert.equal(r.remRssi,  ENCODED.radio_status.remrssi);
    assert.equal(r.txbuf,    ENCODED.radio_status.txbuf);
    assert.equal(r.noise,    ENCODED.radio_status.noise);
    assert.equal(r.remNoise, ENCODED.radio_status.remnoise);
    assert.equal(r.rxErrors, ENCODED.radio_status.rxerrors);
    assert.equal(r.fixed,    ENCODED.radio_status.fixed);
  });

  test(`${version}: a corrupted checksum is rejected`, () => {
    // The other half of the CRC contract. Accepting a reference frame proves the
    // algorithm matches; rejecting a tampered one proves the check is load-bearing
    // rather than decorative.
    const raw = Buffer.from(VECTORS[version].sys_status, 'hex');
    for (const flip of [1, 2]) {
      const bad = Buffer.from(raw);
      bad[bad.length - flip] ^= 0xFF;
      const d = driver();
      feed(d, bad);
      assert.equal(d.telemetry.battery, null,
        `a frame with checksum byte ${flip} corrupted must not be decoded`);
    }
  });

  test(`${version}: a corrupted PAYLOAD is rejected by the checksum`, () => {
    // Tampering with the data rather than the checksum. This is the case that
    // matters on a noisy serial link: a flipped voltage byte must not become a
    // plausible battery reading.
    const raw = Buffer.from(VECTORS[version].sys_status, 'hex');
    const bad = Buffer.from(raw);
    const headerLen = raw[0] === 0xFD ? 10 : 6;
    bad[headerLen + 14] ^= 0xFF;          // voltage_battery low byte
    const d = driver();
    feed(d, bad);
    assert.equal(d.telemetry.battery, null, 'a payload-corrupted frame must not be decoded');
  });
}

test('reference frames are accepted when split across arbitrary chunk boundaries', () => {
  // The parser is fed by socket data events, which split wherever TCP decides.
  const hex = VECTORS.v2.sys_status;
  const raw = Buffer.from(hex, 'hex');
  for (let cut = 1; cut < raw.length; cut++) {
    const d = driver();
    feed(d, raw.subarray(0, cut).toString('hex'));
    feed(d, raw.subarray(cut).toString('hex'));
    assert.notEqual(d.telemetry.battery, null, `must decode when split at byte ${cut}`);
    assert.equal(d.telemetry.battery.voltageV, ENCODED.sys_status.voltage_mV / 1000);
  }
});

test('a back-to-back stream of every reference frame decodes all of them', () => {
  const d = driver();
  const stream = Object.values(VECTORS.v2).join('') + Object.values(VECTORS.v1).join('');
  feed(d, stream);
  assert.notEqual(d.telemetry.heartbeat, null);
  assert.notEqual(d.telemetry.battery, null);
  assert.notEqual(d.telemetry.power, null);
  assert.notEqual(d.telemetry.radio, null);
  assert.equal(d.telemetry.power.flags, ENCODED.power_status.flags);
});

test('non-magic leading garbage is skipped and the following frame decodes', () => {
  // The clean resync case: bytes that cannot start a frame are dropped one at a
  // time until a real magic byte is found.
  const d = driver();
  feed(d, '00112233445566' + VECTORS.v2.power_status);
  assert.notEqual(d.telemetry.power, null, 'must resync onto the valid frame');
  assert.equal(d.telemetry.power.flags, ENCODED.power_status.flags);
});

test('a bogus magic byte claiming a huge payload recovers once enough data arrives', () => {
  // A corrupted length byte does NOT swallow the following frame, but it does make
  // the parser wait: it cannot know the length is wrong until it has enough bytes
  // to test the checksum. That wait is bounded by the largest possible frame
  // (~280 bytes for a signed v2), which is the honest guarantee — not "the next
  // frame decodes immediately".
  //
  // Asserting the bounded version rather than the immediate one matters: an
  // earlier draft of this test assumed immediate recovery, failed, and looked like
  // a parser defect when it was the test's expectation that was wrong.
  const d = driver();
  feed(d, 'fefd' + '00'.repeat(6));                    // v1 magic, claims 253 bytes
  assert.equal(d.telemetry.power, null, 'not enough data yet — waiting is correct');

  feed(d, VECTORS.v2.power_status + '00'.repeat(300));  // now past the claimed length
  assert.notEqual(d.telemetry.power, null,
    'once the claimed frame length is exceeded the parser must resync and decode');
  assert.equal(d.telemetry.power.flags, ENCODED.power_status.flags);
});

test('an unknown message type does not consume a valid frame that follows it', () => {
  // We hold no CRC_EXTRA for most of what the flight controller streams, so those
  // frames cannot be verified. Their declared length is therefore only trusted
  // when the byte past it looks like another frame start — otherwise a corrupted
  // length on an unknown message would eat the next real one.
  const d = driver();
  // msgId 30 (ATTITUDE) — not decoded here. Declared payload length 2, so the
  // claimed frame is 14 bytes and is fully buffered: the lookahead can therefore
  // actually run. The length is a lie (real ATTITUDE is 28), so the byte just past
  // the claimed frame is not a magic byte and the parser must resync rather than
  // trust it. Keeping the claim SMALL is the point — a large claim would make the
  // parser wait for more data instead, which is a different (also safe) path.
  const bogus = Buffer.from([0xFD, 0x02, 0, 0, 0, 1, 1, 30, 0, 0, 0xAA, 0xBB]);
  feed(d, bogus.toString('hex') + VECTORS.v2.power_status);
  assert.notEqual(d.telemetry.power, null,
    'an unverifiable frame with a bad length must not swallow the next valid frame');
  assert.equal(d.telemetry.power.flags, ENCODED.power_status.flags);
});

// ── v2 incompatibility flags ─────────────────────────────────────────────────

test('a v2 frame with an unknown incompatibility flag is discarded', () => {
  // MAVLink requires a receiver to DISCARD any frame carrying an incompat flag it
  // does not understand, because such a flag can change the framing itself.
  // Previously only bit 0 (signed) was inspected and every other bit was ignored,
  // so a frame claiming an unsupported extension was still decoded — a Codex
  // review built a CRC-valid HEARTBEAT with incompat_flags=0x02 and the parser
  // accepted it as the autopilot.
  const bad = Buffer.from(VECTORS.v2.heartbeat, 'hex');
  bad[2] = 0x02;                       // unknown incompat flag
  const d = driver();
  feed(d, reseal(bad).toString('hex'));   // RE-SEALED, so only the flag check can reject it
  assert.equal(d.telemetry.heartbeat, null,
    'a CRC-valid frame with an unknown incompatibility flag must still be discarded');
  assert.equal(d.pixhawkHeartbeatSeen, false,
    'and must certainly not be accepted as the autopilot heartbeat');
});

test('the known signed flag is still handled rather than rejected outright', () => {
  // Bit 0 is understood: it appends a 13-byte signature. Such a frame must not be
  // treated as unknown-flagged, and its trailing signature must be consumed so a
  // following frame still parses.
  const raw = Buffer.from(VECTORS.v2.power_status, 'hex');
  const signed = Buffer.concat([Buffer.from(raw), Buffer.alloc(13, 0xAB)]);
  signed[2] = 0x01;
  // Recompute nothing: flipping incompat invalidates the CRC, so this frame is
  // expected to be rejected on CRC. What matters is that the parser treats the
  // 13-byte signature as part of THIS frame and then recovers.
  const d = driver();
  feed(d, signed.toString('hex') + VECTORS.v2.sys_status);
  assert.notEqual(d.telemetry.battery, null,
    'the parser must recover and decode the frame following a signed one');
});

// ── Source attribution ───────────────────────────────────────────────────────

test('telemetry from a foreign system is ignored, not merged', () => {
  // sysId was captured but only HEARTBEAT checked it, so SYS_STATUS, POWER_STATUS
  // and PARAM_VALUE accepted data from any system on the link. That matters more
  // now that the parameter overlay is applied on connect and the heartbeat exists
  // to VERIFY it: a foreign vehicle able to populate verifiedCriticalParams would
  // make that verification meaningless.
  const foreign = Buffer.from(VECTORS.v2.sys_status, 'hex');
  foreign[5] = 99;                      // v2 sysid byte
  const d = driver();
  feed(d, reseal(foreign).toString('hex'));   // RE-SEALED: only the sysId gate can reject it
  assert.equal(d.telemetry.battery, null,
    'CRC-valid battery data from a foreign system must still be ignored');

  // And the same for PARAM_VALUE, which is the one that actually matters: a
  // foreign system able to populate verifiedCriticalParams would make the
  // parameter verification the overlay depends on completely meaningless.
  assert.equal(d.verifiedCriticalParams.size, 0);
});

test('a CRC-valid but SHORT v1 payload is rejected rather than zero-padded', () => {
  // v1 payload lengths are fixed; only v2 zero-trims. Padding a short v1 frame
  // invents field values from nothing. Codex built a CRC-valid 6-byte v1 HEARTBEAT
  // that was padded, accepted, and triggered the parameter overlay.
  const full = Buffer.from(VECTORS.v1.heartbeat, 'hex');   // 9-byte payload
  // Rebuild as a 6-byte payload: header(6) + payload(6) + crc(2)
  const short = Buffer.alloc(6 + 6 + 2);
  full.copy(short, 0, 0, 6);          // reuse the header
  short[1] = 6;                       // declare the short length
  full.copy(short, 6, 6, 12);         // first 6 payload bytes
  const d = driver();
  feed(d, reseal(short).toString('hex'));
  assert.equal(d.telemetry.heartbeat, null,
    'a short v1 payload must be rejected, not padded into plausible field values');
  assert.equal(d.pixhawkHeartbeatSeen, false);
});

test('telemetry from the configured target system is accepted', () => {
  // The other direction, so the check above cannot pass by rejecting everything.
  const d = driver({ mavproxy_target_system: 1 });
  feed(d, VECTORS.v2.sys_status);
  assert.notEqual(d.telemetry.battery, null);
  assert.equal(d.telemetry.battery.voltageV, ENCODED.sys_status.voltage_mV / 1000);
});

// ── Source attribution, properly ─────────────────────────────────────────────
//
// The first version of this section was rejected twice over. It asserted only that
// an initially-empty verifiedCriticalParams stayed empty without ever feeding a
// PARAM_VALUE frame — so it proved nothing — and the blanket sysId gate it was
// meant to cover broke real SiK telemetry. These vectors were generated by
// pymavlink on rover3 with the exact source system/component a real device uses.
const ATTRIB = {
  // PARAM_VALUE SERVO1_FUNCTION=26 from the autopilot: sys 1, comp 1.
  param_value_ok:           'fd1900000001011600000000d04101000000534552564f315f46554e4354494f4e00099707',
  // The same param from a FOREIGN component on the right system.
  param_value_foreign_comp: 'fd1900000001631600000000d04101000000534552564f315f46554e4354494f4e00091d04',
  // RADIO_STATUS exactly as SiK firmware emits it: source system 51 (ASCII '3'),
  // component 68 — deliberately NOT the autopilot's sysId.
  radio_status_sik:         'fd0900000033446d000002000100b4aa5f2823d9ee',
};

test('a PARAM_VALUE from the autopilot verifies a critical parameter', () => {
  // The positive case, so the rejection tests below cannot pass by rejecting
  // everything. SERVO1_FUNCTION=26 matches EXPECTED_CRITICAL_PARAMS.
  const d = driver();
  feed(d, ATTRIB.param_value_ok);
  assert.ok(d.verifiedCriticalParams.has('SERVO1_FUNCTION'),
    'a legitimate read-back must verify the parameter');
});

test('a PARAM_VALUE from a foreign COMPONENT does not verify anything', () => {
  // compId was not checked at all: a CRC-valid PARAM_VALUE from sysId 1 / compId 99
  // added entries to verifiedCriticalParams. That makes the verification the
  // parameter overlay depends on forgeable by anything else sharing the link.
  const d = driver();
  feed(d, ATTRIB.param_value_foreign_comp);
  assert.equal(d.verifiedCriticalParams.size, 0,
    'a read-back from the wrong component must not count as verification');
});

test('a PARAM_VALUE from a foreign SYSTEM does not verify anything', () => {
  const foreign = Buffer.from(ATTRIB.param_value_ok, 'hex');
  foreign[5] = 99;                       // v2 sysid
  const d = driver();
  feed(d, reseal(foreign).toString('hex'));
  assert.equal(d.verifiedCriticalParams.size, 0);
});

test('RADIO_STATUS from a real SiK radio IS accepted despite a foreign sysId', () => {
  // The regression this branch introduced and review caught. RADIO_STATUS describes
  // the LINK and is emitted by the radio, not the autopilot — SiK uses source
  // system 51. A blanket target-system gate silently dropped the radio telemetry
  // this branch exists to add, and rover3 has no SiK radio fitted to reveal it.
  const d = driver();
  feed(d, ATTRIB.radio_status_sik);
  assert.notEqual(d.telemetry.radio, null,
    'SiK RADIO_STATUS must be accepted even though its sysId is not the autopilot');
  assert.equal(d.telemetry.radio.rssi, 180);
  assert.equal(d.telemetry.radio.remRssi, 170);
});

test('autopilot state from a foreign system is still rejected', () => {
  // The RADIO_STATUS exemption must not become a general hole.
  const foreign = Buffer.from(VECTORS.v2.sys_status, 'hex');
  foreign[5] = 51;                       // pretend to be the radio
  const d = driver();
  feed(d, reseal(foreign).toString('hex'));
  assert.equal(d.telemetry.battery, null,
    'battery state is autopilot state and must come from the configured system');
});

// ── Invalid flight-controller percentages ────────────────────────────────────

test('a flight-controller percentage above 100 is rejected, not displayed', () => {
  // battery_remaining is a signed byte, so it carries 1..127, but only 1..100 is a
  // valid percentage. 127 was being labelled 'flightcontroller', rendered as 127%,
  // and — because it is above any warning threshold — it CLEARED the low-battery
  // warning while the pack sat at the empty voltage.
  const raw = Buffer.from(VECTORS.v2.sys_status, 'hex');
  for (const bogus of [101, 120, 127]) {
    const bad = Buffer.from(raw);
    // sys_status is zero-trimmed to 17 bytes here, so extend it to carry offset 30.
    const full = Buffer.alloc(10 + 31 + 2);
    bad.copy(full, 0, 0, 10);
    full[1] = 31;
    bad.copy(full, 10, 10, 10 + bad[1]);
    full.writeInt8(bogus, 10 + 30);
    const d = driver({ battery_empty_volts: 6.0, battery_full_volts: 8.4 });
    feed(d, reseal(full).toString('hex'));
    assert.notEqual(d.telemetry.battery, null, 'the frame itself is valid');
    assert.notEqual(d.telemetry.battery.pctSource, 'flightcontroller',
      `${bogus}% must not be attributed to the flight controller`);
    assert.notEqual(d.telemetry.battery.remainingPct, bogus,
      `${bogus}% must never be reported as the remaining percentage`);
  }
});

test('a valid flight-controller percentage at the boundaries is still accepted', () => {
  for (const good of [1, 50, 100]) {
    const full = Buffer.alloc(10 + 31 + 2);
    const raw = Buffer.from(VECTORS.v2.sys_status, 'hex');
    raw.copy(full, 0, 0, 10);
    full[1] = 31;
    raw.copy(full, 10, 10, 10 + raw[1]);
    full.writeInt8(good, 10 + 30);
    const d = driver();
    feed(d, reseal(full).toString('hex'));
    assert.equal(d.telemetry.battery.remainingPct, good);
    assert.equal(d.telemetry.battery.pctSource, 'flightcontroller');
  }
});

// ── Unknown-length recovery must not consume a valid frame at EOF ─────────────

test('an unknown frame whose false length ends at the buffer end does not consume it', () => {
  // The lossy case review found: the declared length was trusted whenever it
  // reached the end of the buffer, because there was no following byte to check.
  // A crafted length ending exactly after an appended valid frame therefore ate
  // both. Waiting is the safe answer — on a 4 Hz stream more data always arrives.
  const good = Buffer.from(VECTORS.v2.power_status, 'hex');
  // Unknown msgId 30, with a length chosen so header+payload+crc lands exactly at
  // the end of the appended valid frame.
  // The length must make the claimed frame end EXACTLY at the buffer end, or the
  // parser returns at the earlier "not enough data yet" check and never reaches the
  // unknown-message branch at all. A first draft used good.length + 2 and was
  // therefore vacuous — it exercised a path that already existed.
  const claimed = good.length;         // header(10) + payload(14) + crc(2) == 26 == buffer
  const bogus = Buffer.concat([
    Buffer.from([0xFD, claimed, 0, 0, 0, 1, 1, 30, 0, 0]),
    good,
    Buffer.from([0xAA, 0xBB]),
  ]);
  assert.equal(bogus.length, 10 + claimed + 2,
    'precondition: the claimed frame must end exactly at the buffer end');
  const d = driver();
  feed(d, bogus.toString('hex'));
  assert.equal(d.telemetry.power, null, 'nothing decoded yet — the parser must wait');

  // Once more data arrives the bogus length is testable and the parser recovers.
  feed(d, VECTORS.v2.power_status);
  assert.notEqual(d.telemetry.power, null,
    'the valid frame must survive rather than being consumed by a bogus length');
  assert.equal(d.telemetry.power.flags, ENCODED.power_status.flags);
});
