// streams/webrtc.js — WebRTC via MediaMTX (https://host:PORT/PATH/whep)
//
// mediamtx.yml is generated at startup from picar-cfg.json — it is not
// committed to git. All camera and WebRTC parameters live in picar-cfg.json
// alongside the h264/mjpeg equivalents.
'use strict';

const fs   = require('fs');
const path = require('path');
const { spawn } = require('child_process');

function generateMediaMTXConfig(cfg, params) {
  const port    = cfg.webrtc_port     || 8889;
  const udpPort = cfg.webrtc_udp_port || 8189;
  const keyPath  = cfg.mediamtx_key  || path.join(__dirname, '..', 'certs', 'key.pem');
  const certPath = cfg.mediamtx_cert || path.join(__dirname, '..', 'certs', 'cert.pem');
  const camPath  = (cfg.webrtc_path  || 'cam').replace(/^\/+/, '');

  return `logLevel: info
logDestinations: [stdout]

# Generated by picar at startup from picar-cfg.json — do not edit by hand.
rtsp: false
rtmp: false
hls: false
srt: false

webrtc: true
webrtcAddress: :${port}
webrtcEncryption: true
webrtcServerKey: ${keyPath}
webrtcServerCert: ${certPath}
webrtcAllowOrigins: ['*']
webrtcLocalUDPAddress: :${udpPort}
webrtcLocalTCPAddress: :${udpPort}
webrtcIPsFromInterfaces: true
webrtcIPsFromInterfacesList: []
webrtcAdditionalHosts: []
webrtcHandshakeTimeout: 20s
webrtcTrackGatherTimeout: 10s

paths:
  ${camPath}:
    source: rpiCamera
    sourceOnDemand: false
    rpiCameraCamID: ${cfg.webrtc_cam_id ?? 0}
    rpiCameraWidth: ${params.width}
    rpiCameraHeight: ${params.height}
    rpiCameraFPS: ${params.fps}
    rpiCameraCodec: ${cfg.webrtc_codec || 'hardwareH264'}
    rpiCameraIDRPeriod: ${params.idr_period}
    rpiCameraBitrate: ${params.bitrate * 1000}
    rpiCameraHardwareH264Profile: ${cfg.webrtc_h264_profile || 'baseline'}
    rpiCameraHardwareH264Level: '${cfg.webrtc_h264_level || '4.1'}'
    rpiCameraDenoise: ${cfg.webrtc_denoise || 'cdn_fast'}
`;
}

module.exports = function createWebRTCStream(config /*, streamServer not used */) {
  const PROTOCOL  = config.webrtc_protocol || 'https';
  const PORT      = config.webrtc_port     || 8889;
  const PATH_NAME = (config.webrtc_path    || 'cam').replace(/^\/+/, '');
  const YML_PATH  = config.mediamtx_yml    || path.join(__dirname, '..', 'mediamtx.yml');

  // Current camera params — mutable via setParams()
  let params = {
    width:      config.webrtc_width        || 480,
    height:     config.webrtc_height       || 360,
    fps:        config.webrtc_fps          || 20,
    bitrate:    config.webrtc_bitrate_kbps || 350,
    idr_period: config.webrtc_idr_period   || 10,
  };

  function writeYml() {
    const content = generateMediaMTXConfig(config, params);
    fs.writeFileSync(YML_PATH, content, 'utf8');
    console.log(`WebRTC: wrote ${YML_PATH}`);
  }

  // Generate the YAML on startup so mediamtx.yml always reflects picar-cfg.json
  writeYml();
  console.log(`WebRTC: WHEP at ${PROTOCOL}://<host>:${PORT}/${PATH_NAME}/whep`);
  console.log(`WebRTC: ${params.width}×${params.height}@${params.fps}fps ${params.bitrate}kbps`);

  // Restart state. A restart takes seconds, and the operator can drag a slider
  // several times in that window; coalesce instead of queueing N restarts, and
  // never run two at once.
  let restarting     = false;
  let restartQueued  = false;
  let restartChild   = null;

  function restartMediamtx() {
    restarting = true;
    restartQueued = false;
    console.log('WebRTC: restarting mediamtx…');
    // spawn, not exec: no shell, and no buffering of output we do not read.
    restartChild = spawn('systemctl', ['restart', 'mediamtx'], { stdio: 'ignore' });
    restartChild.on('error', (e) => {
      console.error('WebRTC: mediamtx restart failed to spawn:', e.message);
      restarting = false;
      restartChild = null;
    });
    restartChild.on('close', (code) => {
      restartChild = null;
      restarting = false;
      if (code === 0) console.log('WebRTC: mediamtx restarted');
      else console.error(`WebRTC: mediamtx restart exited ${code}`);
      // Apply whatever the operator settled on while this restart was running.
      if (restartQueued) restartMediamtx();
    });
  }

  return {
    clientCount() { return 0; },
    stop() {
      // Do not leave a restart child behind on shutdown.
      if (restartChild) { restartChild.kill('SIGTERM'); restartChild = null; }
      restartQueued = false;
    },

    setParams(newParams) {
      if (newParams.width      !== undefined) params.width      = newParams.width;
      if (newParams.height     !== undefined) params.height     = newParams.height;
      if (newParams.fps        !== undefined) params.fps        = newParams.fps;
      if (newParams.bitrate    !== undefined) params.bitrate    = newParams.bitrate;
      if (newParams.idr_period !== undefined) params.idr_period = newParams.idr_period;
      writeYml();

      // ASYNCHRONOUS on purpose. This used to be execSync, which blocks the Node
      // event loop for the whole duration of a systemd unit restart — seconds.
      // Everything else in this process stops during that: the Socket.IO control
      // stream, the 20 Hz RC override loop, and every fail-safe timer. So changing
      // a video slider could freeze the control path while the vehicle was armed
      // and moving. A video setting must never be able to stall C2.
      if (restarting) {
        console.log('WebRTC: mediamtx restart already in flight, coalescing');
        restartQueued = true;
        return;
      }
      restartMediamtx();
    },

    getStreamConfig() {
      return {
        codec:    'webrtc',
        protocol: PROTOCOL,
        port:     PORT,
        path:     PATH_NAME,
        width:    params.width,
        height:   params.height,
        fps:      params.fps,
        bitrate:  params.bitrate,
      };
    },
  };
};
