// streams/webrtc.js — WebRTC via MediaMTX (https://host:PORT/PATH/whep)
//
// mediamtx.yml is generated at startup from picar-cfg.json — it is not
// committed to git. All camera and WebRTC parameters live in picar-cfg.json
// alongside the h264/mjpeg equivalents.
'use strict';

const fs   = require('fs');
const http = require('http');
const path = require('path');
const { spawn } = require('child_process');

// ICE-TCP is OPT-IN, and off by default. This is a safety-relevant default, not a
// preference.
//
// MEASURED ON ROVER3, 2026-08-06. Every WebRTC session during a failed out-of-sight drive
// negotiated ICE over **TCP**, never UDP:
//
//   [session e7b1b545] peer connection established,
//     local candidate: host/tcp/192.168.10.224/8189, remote candidate: prflx/tcp/…
//
// UDP 8189 was bound and listening and the rover has no firewall, so UDP was available on
// the rover's side and simply lost the connectivity checks across that path. WebRTC then
// did what ICE is designed to do — fell back to the next candidate — and that is the
// problem: **the fallback is silent, and TCP is the wrong transport for real-time video.**
// It keeps WebRTC's assumption that it may shed media freely while running on a transport
// with head-of-line blocking that will not let it. The observed result was back-pressure
// into MediaMTX's pipe and a starved hardware encoder: 544 `ioctl(VIDIOC_QBUF) failed` in
// 112 s at only 200 kbps offered, with video stopping for every viewer until the session
// was torn down.
//
// So the default is now UDP or nothing. A link that cannot carry UDP fails immediately and
// visibly, which is strictly better than degrading into a transport that also takes the
// control path down with it — video and commands share half-duplex airtime, and the same
// drive logged 12 `no input for 1000 ms` fail-safe trips in ~100 s.
//
// Verified from the browser side with getStats() on the same day: with UDP reachable the
// selected pair is `prflx/udp/… ↔ host/udp/<rover>:8189`, succeeded and nominated. Chrome
// mDNS-obfuscates its own host candidate, which is why the rover observes `prflx` rather
// than `host` — that is expected and not a symptom.
//
// Set `webrtc_ice_tcp: true` to restore the old behaviour deliberately, knowing the cost.
function generateMediaMTXConfig(cfg, params) {
  const port    = cfg.webrtc_port     || 8889;
  const udpPort = cfg.webrtc_udp_port || 8189;
  const apiPort = cfg.mediamtx_api_port || 9997;
  // Strict `=== true`: any other value, including a truthy string from a hand-edited
  // overlay, leaves the safe default in place rather than silently enabling TCP.
  const iceTcp  = cfg.webrtc_ice_tcp === true;
  // Omitted entirely rather than set empty — MediaMTX treats an absent key as "no TCP
  // listener", and an empty string has meant "listen on all interfaces" in some config
  // parsers. Absent is the unambiguous form.
  const iceTcpLine = iceTcp ? `webrtcLocalTCPAddress: :${udpPort}\n` : '';
  const keyPath  = cfg.mediamtx_key  || path.join(__dirname, '..', 'certs', 'key.pem');
  const certPath = cfg.mediamtx_cert || path.join(__dirname, '..', 'certs', 'cert.pem');
  const camPath  = (cfg.webrtc_path  || 'cam').replace(/^\/+/, '');

  return `logLevel: info
logDestinations: [stdout]

# Generated by picar at startup from picar-cfg.json — do not edit by hand.
# The API is bound to LOOPBACK ONLY and exists for one reason: reading how many clients are
# pulling the camera. Before this, clientCount() returned a hardcoded 0 - a stub - so a
# second viewer was invisible, which is how a forgotten browser tab streamed through the
# middle of a range test on 2026-08-06, discarding ~42 frames/s while the operator was out
# at distance and nothing on the rover said so. Loopback only: this is diagnostic data on a
# server with no authentication (invariant 1 is open); it must not be reachable off-box.
api: yes
apiAddress: 127.0.0.1:${apiPort}

rtsp: false
rtmp: false
hls: false
srt: false

webrtc: true
webrtcAddress: :${port}
webrtcEncryption: true
webrtcServerKey: ${keyPath}
webrtcServerCert: ${certPath}
webrtcAllowOrigins: ['*']
webrtcLocalUDPAddress: :${udpPort}
${iceTcpLine}webrtcIPsFromInterfaces: true
webrtcIPsFromInterfacesList: []
webrtcAdditionalHosts: []
webrtcHandshakeTimeout: 20s
webrtcTrackGatherTimeout: 10s

paths:
  ${camPath}:
    source: rpiCamera
    sourceOnDemand: false
    rpiCameraCamID: ${cfg.webrtc_cam_id ?? 0}
    rpiCameraWidth: ${params.width}
    rpiCameraHeight: ${params.height}
    rpiCameraFPS: ${params.fps}
    rpiCameraCodec: ${cfg.webrtc_codec || 'hardwareH264'}
    rpiCameraIDRPeriod: ${params.idr_period}
    rpiCameraBitrate: ${params.bitrate * 1000}
    rpiCameraHardwareH264Profile: ${cfg.webrtc_h264_profile || 'baseline'}
    rpiCameraHardwareH264Level: '${cfg.webrtc_h264_level || '4.1'}'
    rpiCameraDenoise: ${cfg.webrtc_denoise || 'cdn_fast'}
`;
}

module.exports = function createWebRTCStream(config /*, streamServer not used */) {
  const PROTOCOL  = config.webrtc_protocol || 'https';
  const PORT      = config.webrtc_port     || 8889;
  const PATH_NAME = (config.webrtc_path    || 'cam').replace(/^\/+/, '');
  const YML_PATH  = config.mediamtx_yml    || path.join(__dirname, '..', 'mediamtx.yml');

  // Current camera params — mutable via setParams()
  let params = {
    width:      config.webrtc_width        || 480,
    height:     config.webrtc_height       || 360,
    fps:        config.webrtc_fps          || 20,
    bitrate:    config.webrtc_bitrate_kbps || 350,
    idr_period: config.webrtc_idr_period   || 10,
  };

  function writeYml() {
    const content = generateMediaMTXConfig(config, params);
    fs.writeFileSync(YML_PATH, content, 'utf8');
    console.log(`WebRTC: wrote ${YML_PATH}`);
  }

  // Generate the YAML on startup so mediamtx.yml always reflects picar-cfg.json
  writeYml();
  console.log(`WebRTC: WHEP at ${PROTOCOL}://<host>:${PORT}/${PATH_NAME}/whep`);
  console.log(`WebRTC: ${params.width}×${params.height}@${params.fps}fps ${params.bitrate}kbps`);

  // Restart state. A restart takes seconds, and the operator can drag a slider
  // several times in that window; coalesce instead of queueing N restarts, and
  // never run two at once.
  let restarting     = false;
  let restartQueued  = false;
  let restartChild   = null;
  let restartTimer   = null;
  let stopped        = false;

  // `systemctl restart` blocks until the unit's job completes, and a unit stuck in
  // `deactivating` blocks for its full TimeoutStopSec — or indefinitely. Moving it
  // off the event loop is not enough: without a bound, one hung restart would leave
  // `restarting` true forever and every later video-param change would be silently
  // coalesced into a restart that never happens.
  const RESTART_TIMEOUT_MS = config.mediamtx_restart_timeout_ms ?? 30000;

  function clearRestartState() {
    if (restartTimer) { clearTimeout(restartTimer); restartTimer = null; }
    restartChild = null;
    restarting = false;
  }

  function restartMediamtx() {
    if (stopped) return;   // never spawn during or after shutdown
    restarting = true;
    restartQueued = false;
    console.log('WebRTC: restarting mediamtx…');
    // spawn, not exec: no shell, and no buffering of output we do not read.
    const child = spawn('systemctl', ['restart', 'mediamtx'], { stdio: 'ignore' });
    restartChild = child;

    restartTimer = setTimeout(() => {
      console.error(`WebRTC: mediamtx restart exceeded ${RESTART_TIMEOUT_MS} ms — killing it`);
      try { child.kill('SIGKILL'); } catch (_) {}
      clearRestartState();
    }, RESTART_TIMEOUT_MS);
    // Must not hold the process open at shutdown.
    if (typeof restartTimer.unref === 'function') restartTimer.unref();

    child.on('error', (e) => {
      console.error('WebRTC: mediamtx restart failed to spawn:', e.message);
      clearRestartState();
    });
    child.on('close', (code) => {
      clearRestartState();
      if (code === 0) console.log('WebRTC: mediamtx restarted');
      else console.error(`WebRTC: mediamtx restart exited ${code}`);
      // Apply whatever the operator settled on while this restart was running.
      if (restartQueued && !stopped) restartMediamtx();
    });
  }

  // ── Reader count ───────────────────────────────────────────────────────────
  //
  // POLLED AND CACHED, never fetched on demand. clientCount() is called from request and
  // telemetry paths, and invariant 9 makes a synchronous or awaited network call there a
  // safety defect — the input watchdog is a setTimeout on the same loop. So the HTTP GET
  // happens on its own unref'd interval with a hard timeout, and the accessor returns
  // whatever the last successful poll saw.
  //
  // `null`, not 0, when the count is UNKNOWN. This replaced `clientCount() { return 0; }`,
  // a stub that claimed zero viewers on every rover forever — and 0 is a real, actionable
  // answer meaning "nobody is watching". Reporting a guess as a measurement is the failure
  // this whole module keeps running into; an unreachable API must be distinguishable from
  // an idle camera.
  let readerCount   = null;
  let readerPollErr = null;

  const API_HOST = '127.0.0.1';
  const API_PORT = config.mediamtx_api_port || 9997;
  const READER_POLL_MS      = Math.max(1000, config.webrtc_reader_poll_ms ?? 3000);
  const READER_TIMEOUT_MS   = 1500;

  function pollReaders() {
    if (stopped) return;
    const req = http.get({
      host: API_HOST, port: API_PORT,
      path: `/v3/paths/get/${encodeURIComponent(PATH_NAME)}`,
      timeout: READER_TIMEOUT_MS,
    }, (res) => {
      // Bound the body. This parses a response from a local service, but an unbounded
      // accumulate on a socket that never ends is a leak whatever is on the other end.
      let body = '', len = 0;
      res.on('data', (c) => {
        len += c.length;
        if (len > 64 * 1024) { req.destroy(); return; }
        body += c;
      });
      res.on('end', () => {
        if (res.statusCode !== 200) {
          readerPollErr = `HTTP ${res.statusCode}`;
          return;
        }
        try {
          const parsed = JSON.parse(body);
          readerCount   = Array.isArray(parsed.readers) ? parsed.readers.length : null;
          readerPollErr = readerCount === null ? 'no readers array in API response' : null;
        } catch (e) {
          readerPollErr = `unparseable API response: ${e.message}`;
        }
      });
    });
    req.on('timeout', () => { readerPollErr = 'API timeout'; req.destroy(); });
    req.on('error', (e) => { readerPollErr = e.message; });
  }

  const readerTimer = setInterval(pollReaders, READER_POLL_MS);
  if (typeof readerTimer.unref === 'function') readerTimer.unref();
  pollReaders();

  return {
    // Number of clients pulling this camera, or null when that could not be determined.
    clientCount() { return readerCount; },
    // Why the count is null, for an operator who needs to tell "nobody watching" from
    // "picar cannot see MediaMTX".
    clientCountError() { return readerPollErr; },
    stop() {
      clearInterval(readerTimer);
      // Latch shutdown BEFORE clearing state. Otherwise a setVideoParams arriving
      // during teardown — which any unauthenticated socket can send, including
      // while SIGINT is being handled — would see restarting still true, queue
      // itself, and then be spawned by the dying child's close handler. That
      // launched a `systemctl restart` during process teardown, tracked by nothing.
      stopped = true;
      restartQueued = false;
      if (restartChild) { try { restartChild.kill('SIGTERM'); } catch (_) {} }
      clearRestartState();
    },

    setParams(newParams) {
      if (newParams.width      !== undefined) params.width      = newParams.width;
      if (newParams.height     !== undefined) params.height     = newParams.height;
      if (newParams.fps        !== undefined) params.fps        = newParams.fps;
      if (newParams.bitrate    !== undefined) params.bitrate    = newParams.bitrate;
      if (newParams.idr_period !== undefined) params.idr_period = newParams.idr_period;
      writeYml();

      // ASYNCHRONOUS on purpose. This used to be execSync, which blocks the Node
      // event loop for the whole duration of a systemd unit restart — seconds.
      // Everything else in this process stops during that: the Socket.IO control
      // stream, the 20 Hz RC override loop, and every fail-safe timer. So changing
      // a video slider could freeze the control path while the vehicle was armed
      // and moving. A video setting must never be able to stall C2.
      if (restarting) {
        console.log('WebRTC: mediamtx restart already in flight, coalescing');
        restartQueued = true;
        return;
      }
      restartMediamtx();
    },

    getStreamConfig() {
      return {
        codec:    'webrtc',
        protocol: PROTOCOL,
        port:     PORT,
        path:     PATH_NAME,
        width:    params.width,
        height:   params.height,
        fps:      params.fps,
        bitrate:  params.bitrate,
      };
    },
  };
};

// Exported for tests. The generated yml is the only place the ICE transport policy is
// expressed, and it reaches MediaMTX as a file rather than as an API call — so without
// this the default that decides whether video can silently fall back to TCP is
// unassertable, which is how it stayed wrong.
module.exports.generateMediaMTXConfig = generateMediaMTXConfig;
