// streams/webrtc.js — WebRTC via MediaMTX (https://host:PORT/PATH/whep)
//
// mediamtx.yml is generated at startup from picar-cfg.json — it is not
// committed to git. All camera and WebRTC parameters live in picar-cfg.json
// alongside the h264/mjpeg equivalents.
'use strict';

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function generateMediaMTXConfig(cfg, params) {
  const port    = cfg.webrtc_port     || 8889;
  const udpPort = cfg.webrtc_udp_port || 8189;
  const keyPath  = cfg.mediamtx_key  || path.join(__dirname, '..', 'certs', 'key.pem');
  const certPath = cfg.mediamtx_cert || path.join(__dirname, '..', 'certs', 'cert.pem');
  const camPath  = (cfg.webrtc_path  || 'cam').replace(/^\/+/, '');

  return `logLevel: info
logDestinations: [stdout]

# Generated by picar at startup from picar-cfg.json — do not edit by hand.
rtsp: false
rtmp: false
hls: false
srt: false

webrtc: true
webrtcAddress: :${port}
webrtcEncryption: true
webrtcServerKey: ${keyPath}
webrtcServerCert: ${certPath}
webrtcAllowOrigins: ['*']
webrtcLocalUDPAddress: :${udpPort}
webrtcLocalTCPAddress: :${udpPort}
webrtcIPsFromInterfaces: true
webrtcIPsFromInterfacesList: []
webrtcAdditionalHosts: []
webrtcHandshakeTimeout: 20s
webrtcTrackGatherTimeout: 10s

paths:
  ${camPath}:
    source: rpiCamera
    sourceOnDemand: false
    rpiCameraCamID: ${cfg.webrtc_cam_id ?? 0}
    rpiCameraWidth: ${params.width}
    rpiCameraHeight: ${params.height}
    rpiCameraFPS: ${params.fps}
    rpiCameraCodec: ${cfg.webrtc_codec || 'hardwareH264'}
    rpiCameraIDRPeriod: ${params.idr_period}
    rpiCameraBitrate: ${params.bitrate * 1000}
    rpiCameraHardwareH264Profile: ${cfg.webrtc_h264_profile || 'baseline'}
    rpiCameraHardwareH264Level: '${cfg.webrtc_h264_level || '4.1'}'
    rpiCameraDenoise: ${cfg.webrtc_denoise || 'cdn_fast'}
`;
}

module.exports = function createWebRTCStream(config /*, streamServer not used */) {
  const PROTOCOL  = config.webrtc_protocol || 'https';
  const PORT      = config.webrtc_port     || 8889;
  const PATH_NAME = (config.webrtc_path    || 'cam').replace(/^\/+/, '');
  const YML_PATH  = config.mediamtx_yml    || path.join(__dirname, '..', 'mediamtx.yml');

  // Current camera params — mutable via setParams()
  let params = {
    width:      config.webrtc_width        || 480,
    height:     config.webrtc_height       || 360,
    fps:        config.webrtc_fps          || 20,
    bitrate:    config.webrtc_bitrate_kbps || 350,
    idr_period: config.webrtc_idr_period   || 10,
  };

  function writeYml() {
    const content = generateMediaMTXConfig(config, params);
    fs.writeFileSync(YML_PATH, content, 'utf8');
    console.log(`WebRTC: wrote ${YML_PATH}`);
  }

  // Generate the YAML on startup so mediamtx.yml always reflects picar-cfg.json
  writeYml();
  console.log(`WebRTC: WHEP at ${PROTOCOL}://<host>:${PORT}/${PATH_NAME}/whep`);
  console.log(`WebRTC: ${params.width}×${params.height}@${params.fps}fps ${params.bitrate}kbps`);

  return {
    clientCount() { return 0; },
    stop() {},

    setParams(newParams) {
      if (newParams.width      !== undefined) params.width      = newParams.width;
      if (newParams.height     !== undefined) params.height     = newParams.height;
      if (newParams.fps        !== undefined) params.fps        = newParams.fps;
      if (newParams.bitrate    !== undefined) params.bitrate    = newParams.bitrate;
      if (newParams.idr_period !== undefined) params.idr_period = newParams.idr_period;
      writeYml();
      try {
        console.log('WebRTC: restarting mediamtx…');
        execSync('systemctl restart mediamtx', { stdio: 'inherit' });
        console.log('WebRTC: mediamtx restarted');
      } catch (e) {
        console.error('WebRTC: mediamtx restart failed:', e.message);
      }
    },

    getStreamConfig() {
      return {
        codec:    'webrtc',
        protocol: PROTOCOL,
        port:     PORT,
        path:     PATH_NAME,
        width:    params.width,
        height:   params.height,
        fps:      params.fps,
        bitrate:  params.bitrate,
      };
    },
  };
};
